[workspace]
members = [
  "cd-aws",
  "cd-cli",
  "cd-haproxy-agent",
  "cd-service-config",
  "cd-systemd",
  "cd-tunnelblick",
  "centerdevice-rs",
  "cssh",
  "cvpn",
  "cweb",
  "cwk",
  "haproxy-agent",
]