[workspace]
members = [
  "cli/cssh",
  "cli/cvpn",
  "cli/cweb",
  "cli/cwk",
  "lib/cd-aws",
  "lib/cd-cli",
  "lib/cd-haproxy-agent",
  "lib/cd-service-config",
  "lib/cd-systemd",
  "lib/cd-tunnelblick",
  "lib/centerdevice-rs",
  "service/haproxy-agent",
]