:toc:
:gh-repo: dennis-kuypers/cdrust
:all-bins: cssh cvpn cwk
= Rust Monorepo

Contains code for various (ops-related) tools written in rust.

== CLI tools

|===
|Tool |

|link:cli/cssh/README.adoc[cssh]
|easily SSH into AWS EC2 instances

|link:cli/cvpn/README.adoc[cvpn]
|control VPN connections (Tunnelblick)

|link:cli/cwk/README.adoc[cwk]
|Workflow helper (PivotalTracker, github, git)

|===

=== ceres substitutes

Replacements for link:https://github.com/CenterDevice/ceres[ceres] features:

* `ceres stories prepare` -> `cwk prep`
* contrib `cssh` script -> `cssh`

=== Install

==== homebrew (OSX)

[source,shell,subs="attributes"]
----
brew tap {gh-repo} git@github.com:{gh-repo}.git
brew install {all-bins}
----

==== from source

_Requires `rust` toolchain. see https://rustup.rs/_.
MSRV=1.58

`cargo install --git ssh://github.com/{gh-repo} {all-bins}`

This will install all binaries to `$HOME/.cargo/bin` (make sure that it's on your `$PATH`)

=== Configuration

All tools are based on the same libraries, and they all share some configuration entries.
When configuring aws related options they will apply to all tools (unless you specify in a tool-specific config file)

==== Profiles

The config system is profile based.

The `default` profile is loaded first.
Then the *selected profile* is loaded.
Finally the `global` profile is loaded and overwrites any previous values.

The *selected profile* is determined either using the CLI switch `-p &lt;profile&gt;`/`--profile &lt;profile&gt;` or by reading the contents of `~/.cd/profile`.

==== Files

The file format is TOML.

|===
|File |Contents

|`~/.cd/default.conf` |fallback values
|`~/.cd/&lt;profile&gt;.conf` |values for selected profile
|`~/.cd/global.conf` |overrides
|`~/.cd/&lt;name&gt;.conf` |cli specific (contains multiple profiles)
|===

*Example*

[source,toml]
----
# default.conf, <profile>.conf or global.conf
[foo]
bar = "hello config"
----

_Effectively configures `foo.bar` to value `hello config`._

In the cli specific file the first configuration level is the profile name, so `&lt;key...&gt;` becomes `&lt;profile&gt;.&lt;key...&gt;`.

To configure `foo.bar` to value `hello config` in the `default` profile you would write:

[source,toml]
----
# <name>.conf
[default.foo]
bar = "hello config"
----

or

[source,toml]
----
# <name>.conf
[default]
foo.bar = "hello config"
----

==== Properties

[#config-log]
==== logging (lib)

The config prefix is `log`.

|===
| Key |Description |Example

|`custom`
|Takes one of `off`, `error`, `warn`, `info`, `debug`, `trace` or a complex configuration according to the link:https://docs.rs/env_logger/0.9.0/env_logger/#enabling-logging[env_logger] documentation.
|`debug`
|===

[#config-aws]
==== aws (lib)

The config prefix is `aws`.

|===
| Key |Description |Example

|profile (string, required)
|The AWS profile to use.
This usually refers to the name of a `~/.aws/config` `profile` section
|`"rol_ops@prod"`

|===

[#config-pivotal]
==== pivotaltracker (lib)

The config prefix is `pivotal`.

|===
| Key |Description |Example

|me (string, required)
|Your `User name` on your link:https://www.pivotaltracker.com/profile[PivotalTracker Profile]. This is used to filter tickets.
|`"albert_einstein"`

|token (string, required)
|Your `api token` on your link:https://www.pivotaltracker.com/profile[PivotalTracker Profile].
|`"1234567890abcdef"`

|project_id (integer, required)
|The project to use. Can be found as part of the url on the web.
|`123456789`

|===

[#config-vpn]
==== vpn (lib)

The config prefix is `vpn`.
The VPN functionality uses tunnelblick.

|===
| Key |Description |Example

|action (string, defaults to `none`)
|The action to take when an application requires VPN.
|`"abort"` (abort and show error)
`"none"` (do not check VPN)

|===

[#config-tunnelblick]
==== tunnelblick (lib)

The config prefix is `tunnelblick`.

|===
| Key |Description |Example

|enabled (boolean, default=false)
|Enables tunnelblick functionality.
|true/false

|connection (string, required if enabled=true)
|The configuration name as shown in the tunnelblick ui
|`"my_vpn_connection"`

|===

[#config-tmux]
==== tmux (lib)

The config prefix is `tmux`.

|===
| Key |Description |Example

|enabled (boolean, default=false)
|Enables tmux functionality.
|true/false

|layout (string, required if enabled=true)
|The layout to apply after spawning a new panel. This is required so that repeated splitting of panels does not lead to an exchaustion of space.
For options see https://www.man7.org/linux/man-pages/man1/tmux.1.html[tmux select-layout]
|`"even-vertical"`

|===
