:toc:
= cssh

cssh spawns ssh sessions by querying for EC2 instances.
It has support for multiplexers, like tmux.

== Usage Example

`cssh <query> [<query>...]`

Query words can have 3 forms

* `i-...` will only be matched against the aws instance id
* numeric values will only match on the end of the name - intended for clustered instances
* anything else will text match on the instance name

Given three instances

* `www_server-fra-i-12345678-01`
* `sql_db_server-dus-i-12345678-01`
* `sql_db_server-dus-i-12345678-02`

Then running...

* `cssh ww` immediately connects to the www_server (single result)
* `cssh db` shows a list of the db servers to pick one to connect to (multiple results)
* `cssh db 2` finds the instance whose name contains both `db` and the cluster instance is `2`, despite the first instance having a literal `2` in its name (single result)
* `cssh --any db` picks any instance returned from AWS and immediately connects to it (multiple results)

== Configuration

`cssh` does not have tool specific settings.

`cssh` requires link:../../README.adoc#config-aws[AWS] and can optionally use link:../../README.adoc#config-tmux[tmux] for multiplexing connections.

== Changelog

**Warning**
_There is no guarantee for output stability.
These tools are intended to be consumed by humans._

=== [Unreleased]

==== Added
- possibility to let cssh check for vpn connectivity, disabled by default. See link:../../README.adoc#config-vpn[vpn] to enable

==== Changed
- be smart about queries with numbers - only match on cluster instances and not on random digits in name

==== Fixes
- remove debug output that was not intended to be printed

=== [cssh 0.2.0]

This is the initial release
