[package]
name = "cweb"
description = "cli helper for webserver related tasks"
version = "0.1.0"
edition = "2021"

[dependencies]
cd-cli = { path = "../../lib/cd-cli" }

anyhow = "1.0"
regex = "1"
serde = { version = "1", features = ["derive"] }
structopt = "0.3"