= cssh
:toc:

A workflow helper.
This is tightly integrated with our current workflow around pivotaltracker, git and github.

== Usage Example

=== prep

* `cwk prep` asks for a story to prepare. (filters by owner=me & state in [started, planned, unstarted])
* `cwk prep <pivotal_story_id_or_url>` prepares the given story

=== on (WIP)

(`cwk on` => "(c) work on)

`cwk on` asks for a story to work on if not provided and sets the stories state to started.
It will also ask for estimation and run the preparation steps just like `cwk prep`.

Currently this command expects an environment variable `INFRA` that points to the infrastructure repository.

== Configuration

`cwk` does not have tool specific settings.

`cwk` requires link:../../README.adoc#config-pivotal[pivotal]

== Changelog

**Warning**
_There is no guarantee for output stability.
These tools are intended to be consumed by humans._

=== [Unreleased]

=== [0.3.0]
==== Added

* `cwk on` command (work in progress)

==== Fixes

* only ask for estimation on Features, not on Bugs etc.

=== [0.2.2]

==== Fixes

* fixed broken check for existing tasks when using `prepare` command

=== [0.2.1]

==== Changes

* now loads story template from `cwk` config key (as documented)

=== [0.2.0]

This is the initial release introducing the `prep` command.

== Goals

* unscheduled (icebox)
* unstarted/planned
* started
* finished
* delivered
* accepted
* rejected

First check for all preconditions

* ticket has to contain the well known tasks
- if not, add them
* ticket description has to contain `# Risk Assessment`
- if not, add default
* ticket has to be estimated
- if not, ask for estimation
* ticket has to be in a valid state to work on
- `unscheduled/accepted/delivered` - nothing (filtered out)
- `unstarted`, `planned` and `rejected` -> auto promote to `started`
- `finished`
* ask if user wants to set back to `started`, because more work is required
* or ask if ticket should be delivered (and all remaining tasks checked/crossed?)

Then

1. ensure that the ticket has the required workflow steps (done, `cwk prep <id>`)
2. ensure the ticket is in the correct state
3. create and check out a local branch `PT-<pivotal_ticket_id>-<some_text>`
4. set the git commit message template to include `[#<pivotal_ticket_id>]`
5. record the fact that we are working on given ticket (or infer information from branch?)

=== Drop out of workspace

1. clear/reset commit message template